---

- name: Enable iptables
  service:
    name=iptables
    state=started
    enabled=yes
  become: yes

- name: Firewall- Allow 80/tcp 0.0.0.0/0
  iptables:
    chain=INPUT
    protocol=tcp
    destination_port=80
    jump=ACCEPT
    action=insert
    comment='Accept global HTTP'
  become: yes

- name: Firewall- Allow 443/tcp 0.0.0.0/0
  iptables:
    chain=INPUT
    protocol=tcp
    destination_port=443
    jump=ACCEPT
    action=insert
    comment='Accept global HTTPS'
  become: yes

- name: Save IPtables rules to disk
  command: service iptables save
  become: yes

- name: Restart Docker to refresh Docker iptables chain
  service:
    name=docker
    state=restarted
    enabled=yes
  become: yes
